#!/usr/bin/env python3
"""Build the Cloud Product Mapping outputs from the JSON data.

Sources:
  data/providers.json        provider list (order, colors, default `enabled` flag)
  data/categories.json       ordered category list
  data/mapping/<id>.json     products per category for each provider
  data/crosswalk/*.json      service-level crosswalks between two providers (e.g. AWS -> Exoscale)

Outputs:
  README.md                  mapping section between the MAPPING markers
  docs/index.html            self-contained interactive page (GitHub Pages ready)
  docs/poster.html           icon-tile poster (full), ?theme=light|dark
  docs/poster-brief.html     icon-tile poster limited to "brief" categories
  (PNG/PDF exports of the posters: scripts/render.py)

Examples:
  python3 scripts/build.py                              # providers with "enabled": true
  python3 scripts/build.py --providers aws,gcp,exoscale # only these, in this order
  python3 scripts/build.py --exclude oracle             # enabled providers minus Oracle
  python3 scripts/build.py --check                      # fail if outputs are out of date

Only the Python standard library is required.
"""

import argparse
import base64
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
SITE = ROOT / "site"
README = ROOT / "README.md"
DOCS_INDEX = ROOT / "docs" / "index.html"
DOCS_POSTER = ROOT / "docs" / "poster.html"
DOCS_POSTER_BRIEF = ROOT / "docs" / "poster-brief.html"

MAPPING_START = "<!-- MAPPING:START (generated by scripts/build.py, do not edit by hand) -->"
MAPPING_END = "<!-- MAPPING:END -->"
TITLE_START = "<!-- TITLE:START -->"
TITLE_END = "<!-- TITLE:END -->"
CROSSWALK_START = "<!-- CROSSWALK:START (generated by scripts/build.py, do not edit by hand) -->"
CROSSWALK_END = "<!-- CROSSWALK:END -->"

BADGES = {
    "marketplace": "Marketplace",
    "roadmap": "Roadmap",
    "workaround": "Workaround",
}

CROSSWALK_STATUS = {
    "native": ("✅", "Native"),
    "marketplace": ("🛒", "Marketplace"),
    "workaround": ("🔧", "Workaround"),
    "none": ("❌", "No equivalent"),
}


def load_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_data():
    providers = load_json(DATA / "providers.json")["providers"]
    categories = load_json(DATA / "categories.json")["categories"]
    category_ids = {c["id"] for c in categories}
    mapping = {}
    for p in providers:
        path = DATA / "mapping" / f"{p['id']}.json"
        mapping[p["id"]] = load_json(path) if path.exists() else {}
        unknown = set(mapping[p["id"]]) - category_ids
        if unknown:
            sys.exit(f"{path.relative_to(ROOT)}: unknown categories {sorted(unknown)}")
    crosswalks = []
    for path in sorted((DATA / "crosswalk").glob("*.json")):
        cw = load_json(path)
        bad = {r["status"] for r in cw["rows"]} - set(CROSSWALK_STATUS)
        if bad:
            sys.exit(f"{path.relative_to(ROOT)}: unknown status {sorted(bad)}")
        crosswalks.append(cw)
    return providers, categories, mapping, crosswalks


def select_providers(providers, only, exclude):
    by_id = {p["id"]: p for p in providers}
    for pid in (only or []) + (exclude or []):
        if pid not in by_id:
            sys.exit(f"Unknown provider '{pid}'. Known: {', '.join(by_id)}")
    if only:
        selected = [by_id[pid] for pid in only]
    else:
        selected = [p for p in providers if p.get("enabled", True)]
    selected = [p for p in selected if p["id"] not in set(exclude or [])]
    if not selected:
        sys.exit("No providers selected.")
    return selected


def item_badge(item):
    kind = item.get("status") or item.get("source")
    return BADGES.get(kind)


# --------------------------------------------------------------------------- README


def readme_title(selected):
    return "# Cloud Product Mapping (" + " vs ".join(p["name"] for p in selected) + ")"


def readme_item(provider, item):
    label = item["name"]
    if provider.get("iconBase") and item.get("icon"):
        label = f'<img src="{provider["iconBase"]}{item["icon"]}.svg" width="16" height="16" alt=""> {label}'
    text = f"[{label}]({item['url']})" if item.get("url") else label
    badge = item_badge(item)
    return f"{text} _({badge})_" if badge else text


def render_readme_mapping(selected, categories, mapping):
    out = []
    for cat in categories:
        rows = [(p, mapping[p["id"]].get(cat["id"], [])) for p in selected]
        rows = [(p, items) for p, items in rows if items]
        if not rows:
            continue
        out.append(f"## **{cat['name']}**\n")
        for p, items in rows:
            out.append(f"### **{p['name']}**\n")
            out.append(" | ".join(readme_item(p, i) for i in items) + "\n")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def selected_crosswalks(selected, crosswalks):
    ids = {p["id"] for p in selected}
    return [cw for cw in crosswalks if cw["from"] in ids and cw["to"] in ids]


def render_readme_crosswalks(selected, crosswalks):
    by_id = {p["id"]: p for p in selected}
    out = []
    for cw in selected_crosswalks(selected, crosswalks):
        src, dst = by_id[cw["from"]], by_id[cw["to"]]
        out.append(f"## {src['name']} → {dst['name']} Service Crosswalk\n")
        out.append(
            "Service-by-service equivalents. "
            + " · ".join(f"{e} {label}" for e, label in CROSSWALK_STATUS.values()) + "\n"
        )
        out.append(f"| Category | {src['name']} service | {dst['name']} | Status | Notes |")
        out.append("|---|---|---|---|---|")
        for r in cw["rows"]:
            items = [readme_item(dst, i) for i in r[cw["to"]]] or ["—"]
            emoji, label = CROSSWALK_STATUS[r["status"]]
            cells = [r["category"], f"[{r['service']}]({r['url']})", "<br>".join(items), f"{emoji} {label}", r.get("note", "")]
            out.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |")
        out.append("")
    return "\n".join(out)


def replace_between(text, start, end, body, path):
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    if not pattern.search(text):
        sys.exit(f"{path.name}: markers {start!r} … {end!r} not found")
    return pattern.sub(lambda _: f"{start}\n{body}{end}", text, count=1)


def build_readme(selected, categories, mapping, crosswalks):
    text = README.read_text(encoding="utf-8")
    text = replace_between(text, TITLE_START, TITLE_END, readme_title(selected) + "\n", README)
    text = replace_between(
        text, MAPPING_START, MAPPING_END,
        "\n" + render_readme_mapping(selected, categories, mapping) + "\n", README,
    )
    text = replace_between(
        text, CROSSWALK_START, CROSSWALK_END,
        "\n" + render_readme_crosswalks(selected, crosswalks) + "\n", README,
    )
    return text


# --------------------------------------------------------------------------- Site


def icon_uri(provider, name):
    """Return a data: URI for icons/<provider>/<name>.svg, or None if there is no such icon."""
    base = provider.get("iconBase")
    path = ROOT / f"{base}{name}.svg" if base and name else None
    if not path or not path.exists():
        return None
    return "data:image/svg+xml;base64," + base64.b64encode(path.read_bytes()).decode("ascii")


def inline_icons(selected, mapping, crosswalks):
    """Return {"<iconBase><icon>": "data:image/svg+xml;base64,…"} for every icon the selected data uses.

    Icons are embedded as data URIs (used via <img>) rather than inline SVG, so the
    vendor SVGs' internal ids and gradients can't clash with each other.
    """
    by_id = {p["id"]: p for p in selected}
    icons = {}

    def add(provider, item):
        uri = icon_uri(provider, item.get("icon"))
        if uri:
            icons.setdefault(provider["iconBase"] + item["icon"], uri)

    for p in selected:
        for items in mapping[p["id"]].values():
            for item in items:
                add(p, item)
    for cw in crosswalks:
        for r in cw["rows"]:
            for item in r[cw["to"]]:
                add(by_id[cw["to"]], item)
    return icons


def build_site(selected, categories, mapping, crosswalks):
    crosswalks = selected_crosswalks(selected, crosswalks)
    payload = {
        "providers": selected,
        "categories": categories,
        "mapping": {p["id"]: mapping[p["id"]] for p in selected},
        "crosswalks": crosswalks,
        "icons": inline_icons(selected, mapping, crosswalks),
        "badges": BADGES,
        "crosswalkStatus": {k: v[1] for k, v in CROSSWALK_STATUS.items()},
    }
    data_json = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    template = (SITE / "template.html").read_text(encoding="utf-8")
    page = (
        template
        .replace("/*__STYLES__*/", (SITE / "styles.css").read_text(encoding="utf-8"))
        .replace("/*__APP__*/", (SITE / "app.js").read_text(encoding="utf-8"))
        .replace("/*__DATA__*/null", data_json)
        .replace("__TITLE__", html.escape(readme_title(selected)[2:]))
    )
    return page


# --------------------------------------------------------------------------- Poster


BADGE_SHORT = {"marketplace": "Marketplace", "roadmap": "Roadmap", "workaround": "Workaround"}


def initials(name):
    words = re.findall(r"[A-Za-z0-9]+", name)
    return ("".join(w[0] for w in words[:2]) or "?").upper()


def poster_tile(provider, item):
    kind = item.get("status") or item.get("source")
    uri = icon_uri(provider, item.get("icon"))
    art = (
        f'<img class="tile__icon" src="{uri}" alt="">'
        if uri
        else f'<span class="tile__icon tile__icon--mono" aria-hidden="true">{html.escape(initials(item["name"]))}</span>'
    )
    tag = f'<span class="tile__tag tile__tag--{kind}">{BADGE_SHORT[kind]}</span>' if kind in BADGE_SHORT else ""
    label = html.escape(item["name"])
    cls = "tile" + (f" tile--{kind}" if kind else "")
    return f'<div class="{cls}">{art}<span class="tile__label">{label}</span>{tag}</div>'


def build_poster(selected, categories, mapping, brief=False):
    cats = [c for c in categories if c.get("brief") or not brief]
    cells = ['<div class="grid__corner"></div>']
    for p in selected:
        logo = icon_uri(p, p.get("logo"))
        mark = f'<img class="provider__logo" src="{logo}" alt="">' if logo else ""
        mark = f'<span class="provider__mark">{mark}</span>'
        cells.append(
            f'<div class="provider" style="--provider:{p["color"]}">{mark}'
            f'<span class="provider__name">{html.escape(p["fullName"] if len(selected) < 4 else p["name"])}</span></div>'
        )
    rows = 0
    for cat in cats:
        items = [mapping[p["id"]].get(cat["id"], []) for p in selected]
        if not any(items):
            continue
        rows += 1
        cells.append(f'<div class="category"><span>{html.escape(cat["name"])}</span></div>')
        for p, its in zip(selected, items):
            tiles = "".join(poster_tile(p, i) for i in its)
            cells.append(f'<div class="cell" style="--provider:{p["color"]}">{tiles}</div>')

    names = " · ".join(p["name"] for p in selected)
    updated = load_json(DATA / "providers.json").get("updated", "")
    legend = "".join(f'<span class="tile__tag tile__tag--{k}">{v}</span>' for k, v in BADGE_SHORT.items())
    page = (SITE / "poster.html").read_text(encoding="utf-8")
    return (
        page
        .replace("/*__STYLES__*/", (SITE / "poster.css").read_text(encoding="utf-8"))
        .replace("__HEADING__", "Cloud Product Mapping" + (" — Brief" if brief else ""))
        .replace("__TITLE_SUFFIX__", " <span class=\"poster__brief\">Brief</span>" if brief else "")
        .replace("__SUBTITLE__", html.escape(names + (f" · Updated {updated}" if updated else "")))
        .replace("__COLUMNS__", str(len(selected)))
        .replace("__GRID__", "\n".join(cells))
        .replace("__LEGEND__", legend)
    )


# --------------------------------------------------------------------------- Main


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--providers", help="comma-separated provider ids to include, in order")
    parser.add_argument("--exclude", help="comma-separated provider ids to exclude")
    parser.add_argument("--no-readme", action="store_true", help="don't touch README.md")
    parser.add_argument("--no-site", action="store_true", help="don't build docs/ pages")
    parser.add_argument("--check", action="store_true", help="exit 1 if generated files are stale")
    args = parser.parse_args()

    split = lambda s: [x.strip() for x in s.split(",") if x.strip()] if s else None
    providers, categories, mapping, crosswalks = load_data()
    selected = select_providers(providers, split(args.providers), split(args.exclude))

    outputs = []
    if not args.no_readme:
        outputs.append((README, build_readme(selected, categories, mapping, crosswalks)))
    if not args.no_site:
        outputs.append((DOCS_INDEX, build_site(selected, categories, mapping, crosswalks)))
        outputs.append((DOCS_POSTER, build_poster(selected, categories, mapping)))
        outputs.append((DOCS_POSTER_BRIEF, build_poster(selected, categories, mapping, brief=True)))

    stale = []
    for path, content in outputs:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        sys.exit("stale: " + ", ".join(str(p.relative_to(ROOT)) for p in stale) + " (run scripts/build.py)")
    counts = ", ".join(
        f"{p['name']} {sum(len(v) for v in mapping[p['id']].values())}" for p in selected
    )
    print(f"providers: {counts}")


if __name__ == "__main__":
    main()
